feat: Track upload progress
Infomaniak/android-SwissTransfer pull request #151
Opened 2024-11-06 08:21 UTC by sirambd

2024-11-06 10:29 UTC, tevincent approved these changes

2024-11-06 11:46 UTC, tevincent approved these changes

2024-11-06 12:23 UTC, LunarX requested changes

2024-11-06 12:23 UTC, LunarX commented on app/src/main/java/com/infomaniak/swisstransfer/workers/UploadWorker.kt
> +        private const val TRANSFER_UUID_TAG = "transfer_result_tag"
Is the actual string key `"transfer_result_tag"` what you actually wanted?

2024-11-06 12:29 UTC, LunarX commented
I once managed to reach this error when clicking on "Send" after building commit `c897300`. Does it ring a bell?

```
13:25:26.041 System.err            W  java.lang.IllegalStateException: The file /data/user/0/com.infomaniak.swisstransfer/files/imported_files/anime-iphone-background-psdmm565oizldbbg.jpg doesn't exists
13:25:26.042 System.err            W  	at com.infomaniak.swisstransfer.workers.UploadFileTask$start$2.invokeSuspend(UploadFileTask.kt:154)
13:25:26.042 System.err            W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
13:25:26.042 System.err            W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
13:25:26.042 System.err            W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
13:25:26.042 System.err            W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
13:25:26.042 System.err            W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
13:25:26.042 System.err            W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

2024-11-06 15:57 UTC, sirambd commented on app/src/main/java/com/infomaniak/swisstransfer/workers/UploadFileTask.kt
> +                    ensureActive()
To close the coroutine writing to the server

2024-11-06 16:06 UTC, sirambd commented on app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/UploadProgressScreen.kt
> +    }
No, it's the good practice

2024-11-06 16:08 UTC, sirambd commented on app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
> +    HandleSendActionResult({ sendActionResult }, selectedTransferType, navigateToUploadProgress)
Not enough to avoid recomposition

2024-11-07 09:08 UTC, LunarX approved these changes

2024-11-07 09:08 UTC, merged