feat: Add network status info when uploading a Transfer
Infomaniak/android-SwissTransfer pull request #197
Opened 2024-11-18 17:08 UTC by KevinBoulongne

2024-11-21 15:36 UTC, LunarX requested changes

2024-11-22 09:32 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
> +private const val orange = 0XFFFF8500
I've asked for the correct color, and added a TODO to not forget about it.

2024-11-22 09:49 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/swisstransfer/ui/theme/ColorDark.kt
> +private const val orange = 0XFFFF8500
Done.

2024-11-27 08:16 UTC, LunarX commented on app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/upload/components/NetworkUnavailable.kt
> +}
Maybe we should add a preview to this component

2024-11-27 08:25 UTC, LunarX approved these changes

2024-11-27 08:35 UTC, merged