Remove file choice bottom sheet
Infomaniak/android-SwissTransfer pull request #204
Opened 2024-11-20 07:52 UTC by LunarX

We decided to not support the gallery choice nor the camera choice, so the bottom sheet is not needed anymore. This PR removes the bottom sheet and resources associated with it. Also, when picking files, instead of opening the bottom sheet, we directly prompt the user for his files from his file system

2024-11-20 15:11 UTC, NicolasBourdin88 approved these changes

2024-11-20 15:11 UTC, TommyDL-Infomaniak approved these changes

2024-11-21 10:33 UTC, KevinBoulongne requested changes

2024-11-21 10:33 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/swisstransfer/ui/screen/newtransfer/importfiles/ImportFilesScreen.kt
> +    LaunchedEffect(Unit) { if (shouldShowInitialFilePick) pickFiles() }
```suggestion
    fun pickFiles() {
        filePickerLauncher.launch(arrayOf("*/*"))
    }

    fun closeTransferOption() {
        showTransferOption = null
    }

    LaunchedEffect(Unit) {
        if (shouldShowInitialFilePick) {
            shouldShowInitialFilePick = false
            pickFiles()
        }
    }
```

2024-11-21 10:37 UTC, KevinBoulongne approved these changes

2024-11-21 10:37 UTC, merged