Implement validity period screen
Infomaniak/android-SwissTransfer pull request #32
Opened 2024-08-21 07:24 UTC by tevincent

2024-08-21 07:35 UTC, LunarX requested changes

2024-08-21 07:35 UTC, LunarX commented on app/src/main/res/values-de/strings.xml
> +    <string name="settingsNotificationsTitle">Wähle Sie eine Präferenz</string>
Same problem where this is using the polite form

2024-08-21 11:03 UTC, tevincent commented on app/src/main/res/values-es/strings.xml
> +    <string name="settingsValidityPeriodTitle">Establezca un periodo de validez por defecto para sus transferencias</string>
I just checked and it's good.

2024-08-22 04:15 UTC, tevincent commented on app/src/main/res/values-it/strings.xml
> +    </plurals>
Yup, validated by valentin.

2024-08-26 15:15 UTC, merged