Use a PreviewParameter to factorize FileUiItem instantiation inside previews
Infomaniak/android-SwissTransfer pull request #88
Opened 2024-10-14 07:02 UTC by LunarX

I was always using the same list of FileUiItems so instead of copy pasting it everywhere, I used this PreviewParameter that serves this very purpose

2024-10-17 07:29 UTC, KevinBoulongne approved these changes

2024-10-17 14:51 UTC, sirambd requested changes

2024-10-17 14:51 UTC, sirambd commented on app/src/main/java/com/infomaniak/swisstransfer/ui/components/SmallFileTile.kt
> +                val file = files[0]
```suggestion
                val file = files.first()
```

2024-10-18 08:41 UTC, sirambd approved these changes

2024-10-18 08:43 UTC, merged